export const translations = {
  ar: {
    nav: {
      home: 'الرئيسية',
      aboutUs: 'من نحن',
      aboutUsInfo: 'معلومات عن اللجنة',
      aboutUsGoals: 'أهداف اللجنة',
      team: 'الفريق',
      discover: 'اكتشف البلدة',
      oldTown: 'البلدة القديمة',
      crafts: 'المهن والحرف',
      architecture: 'الطبيعة العمرانية',
      ibrahimiMosque: 'الحرم الإبراهيمي',
      achievements: 'إنجازات البلدة',
      donations: 'التبرعات',
      contact: 'تواصل معنا',
    },
    hero: {
      title1: 'إرث الأجداد',
      title2: 'وأمانة الأجيال',
      scroll: 'اسحب لاستكشاف المزيد',
    },
    cards: {
      brandStory: 'البلدة القديمة',
      brandStorySubtitle: 'تراث عريق وحضارة ممتدة',
      brandElements: 'الحرم الإبراهيمي',
      brandElementsSubtitle: 'معلم إيماني وتاريخي',
      launchVideo: 'مبنى اللجنة',
      launchVideoSubtitle: 'مركز إعمار وتطوير',
    },
    sections: {
      manifesto: 'نحفظ التراث، ونُحيي روح المكان، ونُعمّرها حجرًا حجرًا، لنرسّخ الهوية ونمنح البلدة القديمة حياةً نابضة تمتدّ إلى الأجيال القادمة.',
      heartTitle: 'هنا الخليل  ',
      heartText:'هنا ينبض التاريخ، فتتجلّى الهوية الفلسطينية بأبهى صورها. هنا، في قلب فلسطين، وُلدت الحكايات، وتعانقت الثقافات، وترسّخت معاني الصمود جيلاً بعد جيل. واليوم، ما تزال الخليل تنبض بعزيمة شعبٍ يعيد البناء بكل فخر، ويصنع الأمل بإرادة لا تنكسر وطموحٍ يلامس المستقبل.',
      storyTitle: 'قصتنا إلى العالم',
      storyText: 'قصتنا ليست قصة دمار، بل قصة إصرارٍ سُطّرت بأقلام أجيال رفضت أن تُوسم بالصراع، حيث أبت إلا أن توقظ من رماد الماضي طموحاً يسترد التراث ويوحّد الهوية ويرسم المستقبل بالأمل ضمن رواية عالمية تكتبها الخليل اليوم بسواعد أبنائها!',
      storyButton: ' تعرف على لجنة الإعمار ',
      uniteText: 'لجنة إعمار الخليل تجمع أبناء المدينة وتُلهم الفخر من خلال مشاريع تعكس آمالهم وتطلعاتهم.',
      uniteSubtitle: '/ كن على اطلاع',
      pressTitle: 'الإعلام و الصحافة',
      footerTitle: 'اكتشف الرؤى والقصص والتحديثات التي تُشكّل ملامح الخليل المتجددة—من إحياء التراث إلى الابتكار المجتمعي والتحوّل الوطني.',
      footerButton: 'اقرأ المزيد',
    },
    about: {
      heroTitle: 'لجنة إعمار الخليل',
      heroParagraph: 'لجنة إعمار الخليل هي هيئة أهلية مستقلة غير ربحية، تأسست من أبناء مدينة الخليل ومحبيها، وتهدف إلى الحفاظ على التراث الحضاري والديني للبلدة القديمة وصون معالمها التاريخية، من خلال تنفيذ مشاريع إعمار وترميم مستدامة وفق أعلى المعايير المهنية والهندسية.',
      heroCta: 'اعرف المزيد',
      vmTitle: 'رؤيتنا ورسالتنا',
      missionTitle: 'رسالتنا',
      missionText: 'العمل على ترميم وإحياء المعالم التاريخية وتطوير البيئة العمرانية والمجتمعية بما يحفظ هوية المدينة ويخدم سكانها وزوارها.',
      visionTitle: 'رؤيتنا',
      visionText: 'أن تبقى البلدة القديمة في الخليل حيّةً بتاريخها، نابضة بأهلها، ومحافظة على أصالتها وتراثها المعماري والثقافي.',
      valuesTitle: 'قيمنا',
      valuesText: 'الأصالة — الاستدامة — الشفافية — العمل المجتمعي — الحفاظ على التراث — خدمة الإنسان والمكان.',
      aboutTitle: 'نبذة عن اللجنة',
      aboutText1: 'تأسست لجنة إعمار الخليل في عام 2010، انطلاقاً من مسؤولية أبناء المدينة تجاه تراثها العريق ومعالمها المباركة.',
      aboutText2: 'منذ ذلك الحين، عملت اللجنة على تنفيذ العديد من مشاريع الترميم والإعمار بمهنية عالية وشراكات فاعلة مع مختلف الجهات المحلية والدولية.',
      aboutCta: 'تواصل معنا',
      timeline: [
        { year: '2010', title: 'تأسيس اللجنة', text: 'انطلاق العمل بمبادرة من أبناء الخليل للحفاظ على إرث المدينة.' },
        { year: '2013', title: 'إطلاق أول المشاريع', text: 'بدء العمل في ترميم عدد من المعالم التاريخية والدينية.' },
        { year: '2016', title: 'توسيع نطاق العمل', text: 'تنفيذ مشاريع أكبر وشراكات أوسع لخدمة المدينة وتراثها.' },
        { year: '2023', title: 'الاستدامة والتطور', text: 'التركيز على الاستدامة وتطوير المشاريع وفق أحدث المعايير.' },
      ],
      stats: [
        { value: '+50', label: 'شريك وداعم' },
        { value: '+300', label: 'متطوع' },
        { value: '+70', label: 'مشروع مكتمل' },
        { value: '+15', label: 'معلم تاريخي مُرمَّم' },
        { value: '+14', label: 'عاماً من العطاء' },
      ],
    },
  },
  en: {
    nav: {
      home: 'Home',
      aboutUs: 'About Us',
      aboutUsInfo: 'Committee Information',
      aboutUsGoals: 'Committee Goals',
      team: 'Team',
      discover: 'Discover the Town',
      oldTown: 'Old Town',
      crafts: 'Crafts & Professions',
      architecture: 'Urban Architecture',
      ibrahimiMosque: 'Ibrahimi Mosque',
      achievements: 'Town Achievements',
      donations: 'Donations',
      contact: 'Contact Us',
    },
    hero: {
      title1: 'Legacy of Our Ancestors',
      title2: 'Trust of Generations',
      scroll: 'Scroll to Explore More',
    },
    cards: {
      brandStory: 'Old Town',
      brandStorySubtitle: 'Ancient Heritage & Extended Civilization',
      brandElements: 'Ibrahimi Mosque',
      brandElementsSubtitle: 'Spiritual & Historical Landmark',
      launchVideo: 'Committee Building',
      launchVideoSubtitle: 'Reconstruction & Development Center',
    },
    sections: {
      manifesto: 'We preserve heritage, revive the spirit of place, and rebuild it stone by stone, to establish identity and give the Old Town a vibrant life that extends to future generations.',
      heartTitle: 'Here is Hebron',
      heartText: 'Here, history pulsates, and Palestinian identity shines in its most glorious form. Here, in the heart of Palestine, stories were born, cultures embraced, and the meaning of steadfastness was instilled generation after generation. And today, Hebron continues to pulsate with the determination of a people who rebuild with pride, forging hope with an unbreakable will and an ambition that touches the future.',
      storyTitle: 'Our Story to the World',
      storyText: 'Our story is not one of destruction, but one of determination written by generations who refused to be defined by conflict. They chose to awaken from the ashes of the past with an ambition that reclaims heritage, unifies identity, and paints the future with hope—a global narrative that Hebron writes today through the efforts of its people!',
      storyButton: 'Learn about the Reconstruction Committee',
      uniteText: 'Hebron Reconstruction Committee unites the city\'s people and inspires pride through projects that reflect their hopes and aspirations.',
      uniteSubtitle: '/ Stay Informed',
      pressTitle: 'Media & Press',
      footerTitle: 'Discover the visions, stories, and updates shaping renewed Hebron—from heritage revival to community innovation and national transformation.',
      footerButton: 'Read More',
    },
    about: {
      heroTitle: 'Hebron Reconstruction Committee',
      heroParagraph: 'The Hebron Reconstruction Committee is an independent non-profit organization founded by the people of Hebron and its supporters. It aims to preserve the cultural and religious heritage of the Old Town and protect its historical landmarks through sustainable reconstruction and restoration projects following the highest professional and engineering standards.',
      heroCta: 'Learn More',
      vmTitle: 'Our Vision & Mission',
      missionTitle: 'Our Mission',
      missionText: 'To restore and revive historical landmarks and develop the urban and social environment in a way that preserves the city\'s identity and serves its residents and visitors.',
      visionTitle: 'Our Vision',
      visionText: 'For Hebron\'s Old Town to remain alive with its history, vibrant with its people, and faithful to its authenticity and architectural and cultural heritage.',
      valuesTitle: 'Our Values',
      valuesText: 'Authenticity — Sustainability — Transparency — Community Work — Heritage Preservation — Service to People and Place.',
      aboutTitle: 'About the Committee',
      aboutText1: 'The Hebron Reconstruction Committee was founded in 2010, driven by the responsibility of the city\'s people toward its rich heritage and blessed landmarks.',
      aboutText2: 'Since then, the committee has carried out numerous restoration and reconstruction projects with high professionalism and active partnerships with various local and international entities.',
      aboutCta: 'Contact Us',
      timeline: [
        { year: '2010', title: 'Founding the Committee', text: 'Work begins through an initiative by the people of Hebron to preserve the city\'s legacy.' },
        { year: '2013', title: 'Launch of First Projects', text: 'Restoration work begins on several historical and religious landmarks.' },
        { year: '2016', title: 'Expanding the Scope', text: 'Larger projects and broader partnerships to serve the city and its heritage.' },
        { year: '2023', title: 'Sustainability & Development', text: 'Focus on sustainability and developing projects according to the latest standards.' },
      ],
      stats: [
        { value: '+50', label: 'Partners & Supporters' },
        { value: '+300', label: 'Volunteers' },
        { value: '+70', label: 'Completed Projects' },
        { value: '+15', label: 'Restored Landmarks' },
        { value: '+14', label: 'Years of Giving' },
      ],
    },
  },
};

export const pressArticles = [
  {
    id: 1,
    titleAr: 'مشروع ترميم البلدة القديمة يدخل مرحلته الثانية',
    titleEn: 'Old Town Restoration Project Enters Second Phase',
    date: 'Jan 15, 2025',
    image: 'https://images.unsplash.com/photo-1580310219243-dbad8c44e576',
  },
  {
    id: 2,
    titleAr: 'افتتاح معرض المهن والحرف التقليدية في البلدة القديمة',
    titleEn: 'Opening of Traditional Crafts Exhibition in the Old Town',
    date: 'Jan 10, 2025',
    image: 'https://images.unsplash.com/photo-1633788229431-a9683c7388dd',
  },
  {
    id: 3,
    titleAr: 'لجنة إعمار الخليل تطلق مبادرة جديدة لدعم الحرفيين',
    titleEn: 'Hebron Reconstruction Committee Launches New Initiative to Support Artisans',
    date: 'Jan 05, 2025',
    image: 'https://images.unsplash.com/photo-1562457141-8c1df886f92c',
  },
];

export const sectionImages = {
  brandStory: '/old-town.webp',
  brandElements: '/pattern.webp',
  launchVideo: '/hrc-building.webp',
  uniteSection: '/hrc-interior.webp',
};