export const translations = {
  ar: {
    nav: {
      home: 'الرئيسية',
      aboutUs: 'من نحن',
      aboutUsInfo: 'معلومات عن اللجنة',
      aboutUsGoals: 'أهداف اللجنة',
      team: 'الفريق',
      discover: 'اكتشف البلدة',
      oldTown: 'البلدة القديمة',
      crafts: 'المهن والحرف',
      architecture: 'الطبيعة العمرانية',
      ibrahimiMosque: 'الحرم الإبراهيمي',
      achievements: 'إنجازات البلدة',
      donations: 'التبرعات',
      contact: 'تواصل معنا',
    },
    hero: {
      title1: 'إرث الأجداد',
      title2: 'وأمانة الأجيال',
      scroll: 'اسحب لاستكشاف المزيد',
    },
    cards: {
      brandStory: 'البلدة القديمة',
      brandStorySubtitle: 'تراث عريق وحضارة ممتدة',
      brandElements: 'الحرم الإبراهيمي',
      brandElementsSubtitle: 'معلم إيماني وتاريخي',
      launchVideo: 'مبنى اللجنة',
      launchVideoSubtitle: 'مركز إعمار وتطوير',
    },
    sections: {
      manifesto: 'نحفظ التراث، ونُحيي روح المكان، ونُعمّرها حجرًا حجرًا، لنرسّخ الهوية ونمنح البلدة القديمة حياةً نابضة تمتدّ إلى الأجيال القادمة.',
      heartTitle: 'الخليل هي القلب',
      heartText: 'في الخليل ينبض التاريخ وتمتزج الحكمة الموروثة بالطموح الحديث، لتتجلّى الخصوصية الفلسطينية، حيث تقع في قلب فلسطين كمدينة وُلدت فيها الحكايات، وتشابكت الثقافات، وترسخت روح الصمود. واليوم، تنبض الخليل بطاقة شعب يعيد البناء بعزّة وطموح وعزيمةٍ لا تنكسر!',
      storyTitle: 'قصتنا إلى العالم',
      storyText: 'قصتنا ليست قصة دمار، بل قصة إصرارٍ سُطّرت بأقلام أجيال رفضت أن تُوسم بالصراع، حيث أبت إلا أن توقظ من رماد الماضي طموحاً يسترد التراث ويوحّد الهوية ويرسم المستقبل بالأمل ضمن رواية عالمية تكتبها الخليل اليوم بسواعد أبنائها!',
      storyButton: 'قصة لجنة الإعمار',
      uniteText: 'لجنة إعمار الخليل تجمع أبناء المدينة وتُلهم الفخر من خلال مشاريع تعكس آمالهم وتطلعاتهم.',
      uniteSubtitle: '/ كن على اطلاع',
      pressTitle: 'الإعلام و الصحافة',
      footerTitle: 'اكتشف الرؤى والقصص والتحديثات التي تُشكّل ملامح الخليل المتجددة—من إحياء التراث إلى الابتكار المجتمعي والتحوّل الوطني.',
      footerButton: 'اقرأ المزيد',
    },
  },
  en: {
    nav: {
      home: 'Home',
      aboutUs: 'About Us',
      aboutUsInfo: 'Committee Information',
      aboutUsGoals: 'Committee Goals',
      team: 'Team',
      discover: 'Discover the Town',
      oldTown: 'Old Town',
      crafts: 'Crafts & Professions',
      architecture: 'Urban Architecture',
      ibrahimiMosque: 'Ibrahimi Mosque',
      achievements: 'Town Achievements',
      donations: 'Donations',
      contact: 'Contact Us',
    },
    hero: {
      title1: 'Legacy of Our Ancestors',
      title2: 'Trust of Generations',
      scroll: 'Scroll to Explore More',
    },
    cards: {
      brandStory: 'Old Town',
      brandStorySubtitle: 'Ancient Heritage & Extended Civilization',
      brandElements: 'Ibrahimi Mosque',
      brandElementsSubtitle: 'Spiritual & Historical Landmark',
      launchVideo: 'Committee Building',
      launchVideoSubtitle: 'Reconstruction & Development Center',
    },
    sections: {
      manifesto: 'We preserve heritage, revive the spirit of place, and rebuild it stone by stone, to establish identity and give the Old Town a vibrant life that extends to future generations.',
      heartTitle: 'Hebron is the Heart',
      heartText: 'In Hebron, history pulsates and inherited wisdom blends with modern ambition to reveal Palestinian uniqueness. Located in the heart of Palestine, it is a city where stories were born, cultures intertwined, and the spirit of resilience took root. Today, Hebron thrives with the energy of people rebuilding with dignity, ambition, and unbreakable determination!',
      storyTitle: 'Our Story to the World',
      storyText: 'Our story is not one of destruction, but one of determination written by generations who refused to be defined by conflict. They chose to awaken from the ashes of the past with an ambition that reclaims heritage, unifies identity, and paints the future with hope—a global narrative that Hebron writes today through the efforts of its people!',
      storyButton: 'Reconstruction Committee Story',
      uniteText: 'Hebron Reconstruction Committee unites the city\'s people and inspires pride through projects that reflect their hopes and aspirations.',
      uniteSubtitle: '/ Stay Informed',
      pressTitle: 'Media & Press',
      footerTitle: 'Discover the visions, stories, and updates shaping renewed Hebron—from heritage revival to community innovation and national transformation.',
      footerButton: 'Read More',
    },
  },
};

export const pressArticles = [
  {
    id: 1,
    titleAr: 'مشروع ترميم البلدة القديمة يدخل مرحلته الثانية',
    titleEn: 'Old Town Restoration Project Enters Second Phase',
    date: 'Jan 15, 2025',
    image: 'https://images.unsplash.com/photo-1580310219243-dbad8c44e576',
  },
  {
    id: 2,
    titleAr: 'افتتاح معرض المهن والحرف التقليدية في البلدة القديمة',
    titleEn: 'Opening of Traditional Crafts Exhibition in the Old Town',
    date: 'Jan 10, 2025',
    image: 'https://images.unsplash.com/photo-1633788229431-a9683c7388dd',
  },
  {
    id: 3,
    titleAr: 'لجنة إعمار الخليل تطلق مبادرة جديدة لدعم الحرفيين',
    titleEn: 'Hebron Reconstruction Committee Launches New Initiative to Support Artisans',
    date: 'Jan 05, 2025',
    image: 'https://images.unsplash.com/photo-1562457141-8c1df886f92c',
  },
];

export const sectionImages = {
  brandStory: 'https://customer-assets.emergentagent.com/job_syrian-ui-replica/artifacts/tved29br_IMG_0005.HEIC.heif',
  brandElements: 'https://customer-assets.emergentagent.com/job_syrian-ui-replica/artifacts/55nm3k4m_IMG_3213.HEIC.heif',
  launchVideo: 'https://customer-assets.emergentagent.com/job_syrian-ui-replica/artifacts/kbsia4ip_IMG_9968.HEIC.heif',
  uniteSection: 'https://customer-assets.emergentagent.com/job_syrian-ui-replica/artifacts/tved29br_IMG_0005.HEIC.heif',
};